<?xml version="1.0" ?>
<!DOCTYPE forum [
<!ELEMENT forum ( personnes, messages) >
<!ELEMENT personnes ( personne*) >
<!ELEMENT messages ( message*) >
<!ELEMENT personne ( nom, prenom, adresse) >
<!ATTLIST personne ref ID #REQUIRED>
<!ELEMENT nom (#PCDATA) >
<!ELEMENT prenom (#PCDATA) >
<!ELEMENT adresse (#PCDATA) >
<!ELEMENT message (expediteur,texte,anterieur?) >
<!ATTLIST message ref ID #REQUIRED>
<!ELEMENT expediteur EMPTY>
<!ATTLIST expediteur ref_pers IDREF #REQUIRED >
<!ELEMENT texte (#PCDATA)>
<!ELEMENT anterieur EMPTY>
<!ATTLIST anterieur ref_msg IDREF #REQUIRED >


] >
<forum>
    <personnes>
        <personne ref="p1">
            <nom>Mohamed</nom>
            <prenom>BenAli</prenom>
            <adresse>Benali@gmail.fr</adresse>
        </personne>
        <personne ref="p2">
            <nom>amin</nom>
            <prenom>daoud</prenom>
            <adresse>lhoste@gmail.fr</adresse>
        </personne>
    </personnes>
    <messages>
        <message ref="m1">
            <expediteur ref_pers="p1" />
            <texte>Bonjour</texte>
        </message>
        <message ref="m2">
            <expediteur ref_pers="p2" />
            <texte>Hello</texte>
        </message>
        <message ref="m3">
            <expediteur ref_pers="p2" />
            <texte>Bonjour, Ca va bien ?</texte>
            <anterieur ref_msg="m1" />
        </message>
        <message ref="m4">
            <expediteur ref_pers="p1" />
            <texte>Ca va !!</texte>
            <anterieur ref_msg="m3" />
        </message>
    </messages>
</forum>

            